name: flutter_cors
description: A script to disable and re-enable CORS for Flutter's Chrome instance
version: 1.0.0
# homepage:

environment:
  sdk: ">=2.15.0 <3.0.0"

dev_dependencies:
  rexios_lints: ^1.0.0
