name: flutter_off_cors
description: A script to disable and re-enable CORS checks for Flutter's Chrome instance & Web Server
version: 1.3.4
homepage: https://github.com/ivan-horchakov/flutter_off_cors

environment:
  sdk: ">=2.15.0 <4.0.0"

dependencies:
  args: ^2.4.2
  pub_update_checker: ^1.2.0
  ansicolor: ^2.0.2

dev_dependencies:
  rexios_lints: ^6.0.1

executables:
  flutteroffcors: flutter_off_cors
