name: flutter_cors
description: A script to disable and re-enable CORS checks for Flutter's Chrome instance
version: 1.3.2
homepage: https://github.com/Rexios80/flutter_cors

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  args: ^2.3.0
  pub_update_checker: ^1.2.0
  ansicolor: ^2.0.1

dev_dependencies:
  rexios_lints: ^4.0.0

executables:
  fluttercors: flutter_cors
