name: flutter_cors
description: A script to disable and re-enable CORS for Flutter's Chrome instance
version: 1.3.0
homepage: https://github.com/Rexios80/flutter_cors

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  args: ^2.3.0
  pub_update_checker: ^1.2.0
dev_dependencies:
  rexios_lints: ^1.0.0

executables:
  fluttercors: flutter_cors